language: python
python:
  - "3.5"
cache: pip
install:
  - npm install --production
  - npm run build
  - pip install -r requirements/dev.txt
  - pip install coveralls
script:
  - py.test --cov
after_success:
  - coveralls
deploy:
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: master
env:
  global:
    secure: UnvkJbwu7jxzb5Faa8jrsheIsoJ3MU53qmNRdazIUW52O7ZrwqZZ0ihZAo/IdWLAvfavBPxXBmm605L5MXJksEvVfj3/y6qG+//gZ0PkPPKa3t5bRcCKBu79/TK6okPJwlL/beJKvNRoALfCIVP2fQa54bu/0h8nMsW9IYG1o3jpKKYo7R1i7psakRohzfDKfn/asgkKgVSp0ppr9i670F9gzScnTAZ8XrBYIYqfAEGfZqxqSmvmLIf1vUXalFKXdSCer9UoF4bbOgDT1iNvbelRmDRQUDA+2tpah/NXr9evvCkGk55T5hjND860W/3sDxLJI0+A+LHbWCGZAacWc2zJ/n/Q6RHIrW1q5rin8QYYcrY8c4CBOjDaS8twqtsjFaot9CWEpgGYP1WUH0xUsav9CfmkkfmM+b7B2mvPqyGOwnOqHg1xscelMqBetwQIjiJUuuoqbqkjgLbXjTu3CLuuSDVI/pBcbae6k3y5tqbcDYNj6gvBwN+4laEnH2N4Z6eRpp1IdrG09NnDHTICQ7+ysAdQsmNLsc7gNr1rl/8iWQ2GMgS7EyLThTN+8PqtPUHvEkvyJ35j7Cp+bOkYAOuQrhXj9GtTPmrzezyMBtnXF81hVdvhGh1M+OlOBbzNQOvMNzHGmgJRx6ZF8+AjCxE3T6JUhE9QkKqpjG9CkJ8=
